"""td003 tickets

Revision ID: td003a
Revises: td002a
Create Date: 2026-10-08 15:52:43.380975
Phase: expand (new tables only)
Task: PR C (TD-003, TD-004)
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import enable_rls

revision: str = "td003a"
down_revision: str | None = "td002a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_counters",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("last_number", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_ticket_counters_tenant"),
    )
    op.create_index(op.f("ix_ticket_counters_tenant_id"), "ticket_counters", ["tenant_id"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'new'"), nullable=False),
        sa.Column("priority", sa.Text(), server_default=sa.text("'P3'"), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("first_replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IS NULL OR category IN ('billing', 'technical', 'account', 'other')",
            name="ck_tickets_category",
        ),
        sa.CheckConstraint("priority IN ('P1', 'P2', 'P3', 'P4')", name="ck_tickets_priority"),
        sa.CheckConstraint(
            "status IN ('new', 'open', 'pending_customer', 'resolved')", name="ck_tickets_status"
        ),
        sa.CheckConstraint("char_length(subject) BETWEEN 1 AND 200", name="ck_tickets_subject_length"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assignee_id"],
            ["users.tenant_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "requester_id"],
            ["users.tenant_id", "users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_tickets_tenant_id"),
        sa.UniqueConstraint("tenant_id", "number", name="uq_tickets_tenant_number"),
    )
    op.create_index("ix_tickets_assignee", "tickets", ["tenant_id", "assignee_id"], unique=False)
    op.create_index("ix_tickets_queue", "tickets", ["tenant_id", "created_at", "id"], unique=False)
    op.create_index("ix_tickets_requester", "tickets", ["tenant_id", "requester_id"], unique=False)
    op.create_index(op.f("ix_tickets_tenant_id"), "tickets", ["tenant_id"], unique=False)
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('public','internal')", name="ck_ticket_messages_kind"),
        sa.CheckConstraint("char_length(body) BETWEEN 1 AND 10000", name="ck_ticket_messages_body_length"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "author_id"],
            ["users.tenant_id", "users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "ticket_id"], ["tickets.tenant_id", "tickets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_messages_tenant_id"), "ticket_messages", ["tenant_id"], unique=False)
    op.create_index(
        "ix_ticket_messages_ticket", "ticket_messages", ["tenant_id", "ticket_id", "created_at"], unique=False
    )
    # Added by hand: autogenerate never emits RLS (migration-writer skill, step 4).
    for table in ("ticket_counters", "tickets", "ticket_messages"):
        enable_rls(table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ticket_messages_ticket", table_name="ticket_messages")
    op.drop_index(op.f("ix_ticket_messages_tenant_id"), table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index(op.f("ix_tickets_tenant_id"), table_name="tickets")
    op.drop_index("ix_tickets_requester", table_name="tickets")
    op.drop_index("ix_tickets_queue", table_name="tickets")
    op.drop_index("ix_tickets_assignee", table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_ticket_counters_tenant_id"), table_name="ticket_counters")
    op.drop_table("ticket_counters")
    # ### end Alembic commands ###
