"""td001 auth tables

Revision ID: td001a
Revises: 0001
Create Date: 2026-10-08
Phase: expand (new tables only; nothing existing changes)
Task: T-001-01 (TD-001, ADR-0002, ADR-0003)
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import enable_rls

TENANT_TABLES = ("users", "email_tokens", "refresh_tokens")

revision: str = "td001a"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("slug ~ '^[a-z0-9-]{3,40}$'", name="ck_tenants_slug_format"),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 200", name="ck_tenants_name_length"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('admin','staff','customer')", name="ck_users_role"),
        sa.CheckConstraint("char_length(email) BETWEEN 3 AND 320", name="ck_users_email_length"),
        sa.CheckConstraint("char_length(name) BETWEEN 1 AND 200", name="ck_users_name_length"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "email", name="uq_users_tenant_email"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_users_tenant_id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_users_tenant", ondelete="RESTRICT"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "email_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("purpose IN ('verify','reset')", name="ck_email_tokens_purpose"),
        sa.CheckConstraint("char_length(token_hash) = 64", name="ck_email_tokens_hash_len"),
        sa.CheckConstraint("expires_at > created_at", name="ck_email_tokens_expiry"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"], ["users.tenant_id", "users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_email_tokens_tenant_id"), "email_tokens", ["tenant_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("char_length(token_hash) = 64", name="ck_refresh_tokens_hash_len"),
        sa.CheckConstraint("expires_at > created_at", name="ck_refresh_tokens_expiry"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"], ["users.tenant_id", "users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_refresh_tokens_family", "refresh_tokens", ["tenant_id", "family_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_tenant_id"), "refresh_tokens", ["tenant_id"], unique=False)
    # Indexes behind the composite FKs, so ON DELETE CASCADE doesn't scan whole tables.
    op.create_index("ix_refresh_tokens_user", "refresh_tokens", ["tenant_id", "user_id"])
    op.create_index("ix_email_tokens_user", "email_tokens", ["tenant_id", "user_id"])
    # Added by hand: autogenerate never emits RLS (migration-writer skill, step 4).
    for table in TENANT_TABLES:
        enable_rls(table)
    # At most one live verify/reset token per user and purpose (TM-014): issuing a new
    # link must first consume the old one, so a leaked older link dies.
    op.create_index(
        "uq_email_tokens_one_live",
        "email_tokens",
        ["tenant_id", "user_id", "purpose"],
        unique=True,
        postgresql_where=sa.text("used_at IS NULL"),
    )
    _lock_down_tenants()


def _app_role() -> str:
    from sqlalchemy.engine import make_url

    from app.core.config import get_settings

    return make_url(get_settings().database_url).username or "PUBLIC"


def _lock_down_tenants() -> None:
    """The registry is not tenant-owned, so the runtime role gets NO table access (ADR-0003).

    It may only call two SECURITY DEFINER functions owned by the migration role. Slugs are
    immutable (trigger), so a stolen session can't rename or enumerate tenants.
    """
    app = _app_role()
    op.execute(f'REVOKE ALL ON tenants FROM "{app}"')
    op.execute(
        """
        CREATE FUNCTION resolve_tenant_slug(p_slug text) RETURNS uuid
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS
        $$ SELECT id FROM tenants WHERE slug = p_slug $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION create_tenant(p_slug text, p_name text) RETURNS uuid
        LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path = public, pg_temp AS
        $$ INSERT INTO tenants (slug, name) VALUES (p_slug, p_name) RETURNING id $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION tenants_slug_immutable() RETURNS trigger LANGUAGE plpgsql AS
        $$ BEGIN
             IF NEW.slug <> OLD.slug THEN RAISE EXCEPTION 'tenant slug is immutable'; END IF;
             RETURN NEW;
           END $$
        """
    )
    op.execute(
        "CREATE TRIGGER tenants_slug_immutable BEFORE UPDATE ON tenants "
        "FOR EACH ROW EXECUTE FUNCTION tenants_slug_immutable()"
    )
    for fn in ("resolve_tenant_slug(text)", "create_tenant(text, text)"):
        op.execute(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC")
        op.execute(f'GRANT EXECUTE ON FUNCTION {fn} TO "{app}"')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS tenants_slug_immutable ON tenants")
    op.execute("DROP FUNCTION IF EXISTS tenants_slug_immutable()")
    op.execute("DROP FUNCTION IF EXISTS create_tenant(text, text)")
    op.execute("DROP FUNCTION IF EXISTS resolve_tenant_slug(text)")
    op.drop_index("uq_email_tokens_one_live", table_name="email_tokens")
    op.drop_index("ix_email_tokens_user", table_name="email_tokens")
    op.drop_index("ix_refresh_tokens_user", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_family", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_email_tokens_tenant_id"), table_name="email_tokens")
    op.drop_table("email_tokens")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
    # ### end Alembic commands ###
